### ISSUE TITLE
Problem with diffab.utils.protein.writers.save_pdb()

### ISSUE THREAD

**Issue by jianfcpku** [luost26/diffab#2]
I'm trying to deploy the model on our local cluster, but got the following error while running the example script.
`> python design_pdb.py ./data/examples/7DK2_AB_C.pdb --config ./configs/test/codesign_single.yml`

> [INFO] Renumbered chain A (H)
[INFO] Renumbered chain B (K)
[INFO] Chain C does not contain valid Fv: Variable chain sequence not recognized: "CPFGEVFNATRFASVYAWNRKRISNCVADYSVLYNSASFSTFKCYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGKIADYNYKLPDDFTGCVIAWNSNNLDSKVGGNYNYLYRLFRKSNLKPFERDISTEIYQAGSTPCNGVEGFNCYFPLQSYGFQPTNGVGYQPYRVVVLSFELLHAPATVCGXXX"
[2022-10-21 23:45:07,716::sample::INFO] Data ID: 7DK2_AB_C.pdb
[2022-10-21 23:45:07,717::sample::INFO] Results will be saved to ./results/codesign_single/7DK2_AB_C.pdb_2022_10_21__23_45_07
[2022-10-21 23:45:07,962::sample::INFO] Loading model config and checkpoints: ./trained_models/codesign_single.pt
[2022-10-21 23:45:13,578::sample::INFO] <All keys matched successfully>
[2022-10-21 23:45:14,304::sample::INFO] Start sampling for: H_CDR1
Traceback (most recent call last):
  File "/gshare/xielab/jianfc/DLTEST/diffab/design_pdb.py", line 4, in <module>
    design_for_pdb(args_from_cmdline())
  File "/gshare/xielab/jianfc/DLTEST/diffab/diffab/tools/runner/design_for_pdb.py", line 177, in design_for_pdb
    save_pdb(data_native, os.path.join(log_dir, variant['tag'], 'REF1.pdb'))       # w/  OpenMM minimization
  File "/gshare/xielab/jianfc/DLTEST/diffab/diffab/utils/protein/writers.py", line 58, in save_pdb
    unique_chain_nb = data['chain_nb'].unique().tolist()
  File "/share/home/jianfc/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/_tensor.py", line 586, in unique
    return torch.unique(self, sorted=sorted, return_inverse=return_inverse, return_counts=return_counts, dim=dim)
  File "/share/home/jianfc/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/_jit_internal.py", line 422, in fn
    return if_false(*args, **kwargs)
  File "/share/home/jianfc/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/_jit_internal.py", line 422, in fn
    return if_false(*args, **kwargs)
  File "/share/home/jianfc/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/functional.py", line 946, in _return_output
    output, _, _ = _unique_impl(input, sorted, return_inverse, return_counts, dim)
  File "/share/home/jianfc/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/functional.py", line 860, in _unique_impl
    output, inverse_indices, counts = torch._unique2(
RuntimeError: std::bad_alloc

Although I have solved the problem temporarily, by changing the Line 58 of `writers.py` from:
`unique_chain_nb = data['chain_nb'].unique().tolist()`
to:
`unique_chain_nb = data['chain_nb'].to('cuda').unique().tolist()`
, running the unique() function on GPU and everything goes well, I'm still wondering the reason why the problem occurs on CPU and how I can fix it.

I'm working on a cluster node with 512GB RAM and two A100-40GB GPU, with python 3.9, pytorch 1.11.0 and cuda 11.3.1.

**Comment by luost26** [comment]
It is weird. I ran the code in Python 3.8. Have you tried changing the version from 3.9 to 3.8?
